defaults:
  - base
  - _self_

name: commonsense
train_dataset: ["commonsense_170k"]
eval_dataset: ["boolq", "piqa", "social_i_qa", "hellaswag", "winogrande", "ARC-Easy", "ARC-Challenge", "openbookqa"]
prompt_template: "%s\n"
trigger_tokens: "the correct answer is "

decoding:
  greedy:
    max_new_tokens: 32
    do_sample: false
  default:
    max_new_tokens: 32
    temperature: 0.1
    top_p: 0.75
    top_k: 40
    num_beams: 4
    do_sample: true