defaults:
  - base
  - _self_

name: ultrafeedback_pair
train_dataset: ["argilla/ultrafeedback-binarized-preferences-cleaned"]
eval_dataset: ["alpaca_eval"]
prompt_template: ${alpaca_prompt_template}
trigger_tokens: "### Response:"

decoding:
  greedy:
    max_length: 2048
    do_sample: false
  default:
    max_length: 2048
    no_repeat_ngram_size: 5
    repetition_penalty: 1.1
    do_sample: false
